### ISSUE TITLE
(1.12.2) Compatibility Textures for Salty Mod and Ice & Fire

### ISSUE THREAD

**Issue by TechnoMysterio** [BetterWithMods/StratifiedOres#1]
Some textures to support Salty Mod's salt ore and Ice & Fire's silver and sapphire ore. Download from MEGA here:

https://mega.nz/#!QHxDyCpJ!WanO-5aHtho77kKwdrH07ses7tOtBgiatx9c0luXBy4

**Comment by primetoxinz** [comment]
Ok, added this finally. Sorry it took so long, completely forgot about it
